import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import client from './apollo-client'
import { gql } from '@apollo/client'

export default function Home({users}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      <div className={styles.grid}>
      {users.map((user)=>(
        <div key={user.id} className={styles.card}>
          <h3>
            <p>
              {user.id} - {user.email}
            </p>
          </h3>


        </div>
      ))}


      </div>

     
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}

export async function getStaticProps(){
  const {data} = await client.query({
    query: gql`
    queryUsersContents{
      id
      flatData{
        email
        userName
        isActive
      }
    }
    
    
    `, 
  })

return{
  props : {
    users: data
  },
};
}